<?php
/**
 * Tuy Website API - Configuration
 * 
 * This file is generated by setup.php during installation.
 * Do not edit manually unless you know what you're doing.
 */

// Database credentials (written by setup.php)
define('DB_HOST', '');
define('DB_NAME', '');
define('DB_USER', '');
define('DB_PASS', '');

// Session configuration
define('SESSION_LIFETIME', 86400); // 24 hours

// Upload configuration
define('UPLOAD_DIR', __DIR__ . '/../uploads/');
define('MAX_IMAGE_SIZE', 10 * 1024 * 1024);  // 10 MB
define('MAX_FILE_SIZE', 25 * 1024 * 1024);   // 25 MB
define('ALLOWED_IMAGE_TYPES', ['image/jpeg', 'image/png', 'image/webp']);
define('ALLOWED_FILE_TYPES', ['application/pdf']);

// ============================================
// Helper Functions
// ============================================

/**
 * Get database connection
 */
function getDB(): mysqli {
    static $conn = null;
    if ($conn === null) {
        $conn = new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);
        if ($conn->connect_error) {
            jsonResponse(500, ['error' => 'Database connection failed']);
            exit;
        }
        $conn->set_charset('utf8mb4');
    }
    return $conn;
}

/**
 * Set CORS and content-type headers
 */
function setCorsHeaders(): void {
    // Allow requests from same origin and common dev origins
    $origin = $_SERVER['HTTP_ORIGIN'] ?? '';
    $allowedOrigins = [
        'https://www.tuybatangas.gov.ph',
        'https://tuybatangas.gov.ph',
        'http://localhost:5173',
        'http://localhost:4173',
    ];

    if (in_array($origin, $allowedOrigins)) {
        header("Access-Control-Allow-Origin: $origin");
    }

    header('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    header('Access-Control-Allow-Headers: Content-Type, Accept');
    header('Access-Control-Allow-Credentials: true');
    header('Content-Type: application/json; charset=utf-8');
}

/**
 * Handle preflight OPTIONS request
 */
function handlePreflight(): void {
    if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
        http_response_code(204);
        exit;
    }
}

/**
 * Send JSON response and exit
 */
function jsonResponse(int $status, array $data): void {
    http_response_code($status);
    echo json_encode($data, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    exit;
}

/**
 * Start admin session
 */
function startSession(): void {
    if (session_status() === PHP_SESSION_NONE) {
        session_set_cookie_params([
            'lifetime' => SESSION_LIFETIME,
            'path' => '/',
            'secure' => isset($_SERVER['HTTPS']),
            'httponly' => true,
            'samesite' => 'Lax',
        ]);
        session_start();
    }
}

/**
 * Check if current request is authenticated
 */
function requireAuth(): void {
    startSession();
    if (empty($_SESSION['admin_id'])) {
        jsonResponse(401, ['error' => 'Unauthorized']);
    }
}

/**
 * Get JSON body from request
 */
function getJsonBody(): array {
    $raw = file_get_contents('php://input');
    $data = json_decode($raw, true);
    return is_array($data) ? $data : [];
}

/**
 * Check if setup has been completed (config has DB credentials)
 */
function isSetupComplete(): bool {
    return DB_HOST !== '' && DB_NAME !== '' && DB_USER !== '' && DB_PASS !== '';
}
